name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # This step specifies the working directory to the location of your frontend code
    - name: Install dependencies
      run: npm ci
      working-directory: ./multi-agents-ui  # <-- Here, specify your correct subfolder path

    # This step specifies the working directory to the location of your frontend code
    - name: Build the project (if present)
      run: npm run build --if-present
      working-directory: ./multi-agents-ui  # <-- Here, specify your correct subfolder path

    # This step specifies the working directory to the location of your frontend code
    - name: Run tests
      run: npm test
      working-directory: ./multi-agents-ui  # <-- Here, specify your correct subfolder path
