name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd ./multi-agents-ui
        npm ci
      working-directory: ./multi-agents-ui

    - name: Build the project (if present)
      run: |
        cd ./multi-agents-ui
        npm run build --if-present
      working-directory: ./multi-agents-ui

    - name: Run tests
      run: |
        cd ./multi-agents-ui
        npm test
      working-directory: ./multi-agents-ui
